server:
  port: 80


spring: 
   datasource:
      url: jdbc:mysql://127.0.0.1:3306/C71-S3-Tsts-music?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: ycsw
      driver-class-name: com.mysql.jdbc.Driver

logging:
   level:
     com:
       yc: debug